services:
  taxi-db:
    image: postgres:latest
    container_name: Taxi-Service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5300:5432"
    restart: unless-stopped

  admin-db:
    image: postgres:latest
    container_name: Admin-Service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5500:5432"
    restart: unless-stopped

  ride-db:
    image: postgres:latest
    container_name: Ride-Service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5600:5432"
    restart: unless-stopped

  dispatch-db:
    image: postgres:latest
    container_name: Dispatch-Service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5800:5432"
    restart: unless-stopped

  finance-db:
    image: postgres:latest
    container_name: Finance-Service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5900:5432"
    restart: unless-stopped
    
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - taxi-service-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:8001,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: >
        taxi.driver.create:1:1,
        taxi.driver.created:1:1,
        taxi.driver.status.change:1:1,
        taxi.driver.status.changed:1:1,
        taxi.vehicle.changed:1:1,
        taxi.vehicle.change:1:1,
        taxi.vehicle.create:1:1,
        account.deleted:1:1,
        admin.created:1:1,
        admin.ban.changed:1:1,
        admin.refind.status.changed:1:1,
        admin.create:1:1,
        ride.assigned:1:1,
        ride.cancelled:1:1,
        ride.completed:1:1,
        ride.requested:1:1,
        ride.started:1:1,
        ride.assignation:1:1,
    depends_on:
      - zookeeper
    networks:
      - taxi-service-network
    volumes:
      - taxi-service-kafka-data:/kafka-data
    ports:
      - '8001:9092'

networks:
  taxi-service-network:
    driver: bridge

volumes:
  taxi-service-kafka-data: